// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeEvent() Event {
	message := NewMessage()
	greeter := NewGreeter(message)
	event := NewEvent(greeter)
	return event
}

func InitializeInterface() *MyFooer {
	myFooer := provideMyFooer()
	return myFooer
}

func InitializeStruct() FooBar {
	fooInt := ProvideFoo()
	barInt := ProvideBar()
	fooBar := FooBar{
		MyFoo: fooInt,
		MyBar: barInt,
	}
	return fooBar
}
